# Generated by Django 2.1.4 on 2019-01-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0003_auto_20190126_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
