# Generated by Django 2.1.4 on 2019-01-26 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0004_exercises_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexercises',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
