# Generated by Django 2.1.4 on 2019-01-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0012_remove_exercises_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='check_result',
            field=models.TextField(default=''),
        ),
    ]
