# Generated by Django 2.1.4 on 2019-01-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0005_auto_20190126_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercises',
            old_name='id_language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='exercises',
            old_name='id_section',
            new_name='section',
        ),
    ]
