# Generated by Django 2.1.4 on 2019-01-27 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0007_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='code_app.Courses'),
            preserve_default=False,
        ),
    ]
