# Generated by Django 2.1.4 on 2019-01-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0008_languages_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='language',
        ),
    ]
