# Generated by Django 2.1.4 on 2019-01-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0009_remove_languages_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='template_path',
            field=models.CharField(default='code_app/python_startcode.html', max_length=100),
        ),
    ]
