# Generated by Django 2.1.4 on 2019-01-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0010_courses_template_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='check_method',
            field=models.IntegerField(choices=[(1, 'funkcja'), (2, 'stdout')], default=1),
        ),
        migrations.AddField(
            model_name='exercises',
            name='check_result',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
