# Generated by Django 2.1.4 on 2019-01-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0013_auto_20190127_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSyntax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('regexp', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='language',
        ),
        migrations.AddField(
            model_name='exercises',
            name='check_syntax',
            field=models.ManyToManyField(to='code_app.CheckSyntax'),
        ),
    ]
